// Generated by gencpp from file get_rs_image/FLIR_image.msg
// DO NOT EDIT!


#ifndef GET_RS_IMAGE_MESSAGE_FLIR_IMAGE_H
#define GET_RS_IMAGE_MESSAGE_FLIR_IMAGE_H

#include <ros/service_traits.h>


#include <get_rs_image/FLIR_imageRequest.h>
#include <get_rs_image/FLIR_imageResponse.h>


namespace get_rs_image
{

struct FLIR_image
{

typedef FLIR_imageRequest Request;
typedef FLIR_imageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FLIR_image
} // namespace get_rs_image


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::get_rs_image::FLIR_image > {
  static const char* value()
  {
    return "a4166222fac24d9abf5822c7d9b15b3b";
  }

  static const char* value(const ::get_rs_image::FLIR_image&) { return value(); }
};

template<>
struct DataType< ::get_rs_image::FLIR_image > {
  static const char* value()
  {
    return "get_rs_image/FLIR_image";
  }

  static const char* value(const ::get_rs_image::FLIR_image&) { return value(); }
};


// service_traits::MD5Sum< ::get_rs_image::FLIR_imageRequest> should match 
// service_traits::MD5Sum< ::get_rs_image::FLIR_image > 
template<>
struct MD5Sum< ::get_rs_image::FLIR_imageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::get_rs_image::FLIR_image >::value();
  }
  static const char* value(const ::get_rs_image::FLIR_imageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::get_rs_image::FLIR_imageRequest> should match 
// service_traits::DataType< ::get_rs_image::FLIR_image > 
template<>
struct DataType< ::get_rs_image::FLIR_imageRequest>
{
  static const char* value()
  {
    return DataType< ::get_rs_image::FLIR_image >::value();
  }
  static const char* value(const ::get_rs_image::FLIR_imageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::get_rs_image::FLIR_imageResponse> should match 
// service_traits::MD5Sum< ::get_rs_image::FLIR_image > 
template<>
struct MD5Sum< ::get_rs_image::FLIR_imageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::get_rs_image::FLIR_image >::value();
  }
  static const char* value(const ::get_rs_image::FLIR_imageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::get_rs_image::FLIR_imageResponse> should match 
// service_traits::DataType< ::get_rs_image::FLIR_image > 
template<>
struct DataType< ::get_rs_image::FLIR_imageResponse>
{
  static const char* value()
  {
    return DataType< ::get_rs_image::FLIR_image >::value();
  }
  static const char* value(const ::get_rs_image::FLIR_imageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GET_RS_IMAGE_MESSAGE_FLIR_IMAGE_H
